### ISSUE TITLE
java.lang.lang.UnsatisfiedlinkError

### ISSUE THREAD

**Issue by jiya1** [wseemann/FFmpegMediaMetadataRetriever#103]
Hi, 
I am trying to extract image from video with FFmpegMediaMetadaRetreiver, it gives me this error :  

process: com.example.ayrojectcutvideo, PID: 12591
java. lang.UnsatisfiedlinkError: dalvik. system. 
PathClassLoader[DexPa 41
thList[ [zip file “!data/app/com.example. ayrojectcutvideo—2/base. ap 40k”] 
,nativeLibraryDirectories=[/data/app/com.example. asrojectcutvid 4]
eo—2/lib/arm, /vendor/lib, /system/lib]]] couldn’t find “libavutil.

 Can you please tell me what is the prblem ?

This is the code : 
   FFmpegMediaMetadataRetriever retriever = new  FFmpegMediaMetadataRetriever();
                                 try {
                                 retriever.setDataSource(videoURL);
                                 Bitmap bitmap = retriever.getFrameAtTime(minValue*1000,FFmpegMediaMetadataRetriever.OPTION_CLOSEST_SYNC );
                                 imgv1.setImageBitmap(bitmap);
                                 } catch (Exception e) {
                                 e.printStackTrace();
                                 }
                                 finally{
                                 retriever.release();
                                 }

**Comment by tuyentangtruong** [comment]
yes, I also got that error.

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "CRYPTO_get_locking_callback" referenced by "**/lib/arm/libavformat.so"...
Please help me out.

**Comment by fabredthunder** [comment]
Me too.

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.**********-1/base.apk"],nativeLibraryDirectories=[/data/app/com.**********-1/lib/arm64, /data/app/com.**********-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libavutil.so"
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                                           at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:124)
                                                                           at com.lacompany.konbini.controllers.managers.StreamManager.getMetadata(StreamManager.java:64)
                                                                           at com.lacompany.konbini.controllers.activities.MainActivity.onCreate(MainActivity.java:108)
                                                                           at android.app.Activity.performCreate(Activity.java:6876)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


Any solution ?

**Comment by LiuLei030504** [comment]
Its same for me.

**Comment by LiuLei030504** [comment]
Seems its doesn't support the "arm64-v8a"

**Comment by wseemann** [comment]
This is fixed in version 1.0.14.

**Comment by bravekingzhang** [comment]
just add 

`-keep class wseemann.media.**{*; }`

 ,to  proguard rule file
