### ISSUE TITLE
setDataSource failed: status = 0xFFFFFFFF with files from assets folder

### ISSUE THREAD

**Issue by raman4793** [wseemann/FFmpegMediaMetadataRetriever#191]
```kotlin
        val mmr = FFmpegMediaMetadataRetriever()
        val videoFile = assets.openFd("test.mp4").fileDescriptor
        Log.d("Logging", " : $videoFile")
        mmr.setDataSource(videoFile)
This is the code that i am using and this seems very similar to #20. I noticed that you already pushed a fix to this bug, but for some reason i am still getting this error. I am using version 1.0.14 and here is my stacktrace

#09-11 15:48:49.227 15668-15668/com.example.ramachandran.videometa D/Logging:  : java.io.FileDescriptor@771891b
09-11 15:48:49.227 15668-15668/com.example.ramachandran.videometa V/MediaMetadataRetrieverJNI: setDataSource
09-11 15:48:49.227 15668-15668/com.example.ramachandran.videometa W/ndran.videomet: Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
09-11 15:48:49.460 15668-15668/com.example.ramachandran.videometa D/AndroidRuntime: Shutting down VM
09-11 15:48:49.463 15668-15668/com.example.ramachandran.videometa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ramachandran.videometa, PID: 15668
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ramachandran.videometa/com.example.ramachandran.videometa.MainActivity}: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFFF
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFFF
        at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(Native Method)
        at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(FFmpegMediaMetadataRetriever.java:201)
        at com.example.ramachandran.videometa.MainActivity.onCreate(MainActivity.kt:25)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

if you notice the first like of the stacktrace the filedescriptor object is set, its not null so I m not sure what is going wrong

**Comment by KnIfER** [comment]
Also happens with files from normal folder. The FileDescriptor version of setDataSource is not stable.

**Comment by DominicPritham** [comment]
I am facing the same issue. Any possible solution?

**Comment by NeighborhoodCoding** [comment]
Me too How to solve this?

**Comment by guzelonur** [comment]
Using the demo app (APK) [here](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/download/v1.0.21/FMMRDemo.apk), I am not able to make the app read files in local storage (aka Internal Memory). It shouts "error". Is there exact URI for making the demo app recognizing local media files with the demo app? Tried many local file paths with no avail. Best regards.
@wseemann
