### ISSUE TITLE
Failed in release Android Application

### ISSUE THREAD

**Issue by Purvik** [wseemann/FFmpegMediaMetadataRetriever#205]
Developed react-native application with `react-native-media-meta` dependency that uses this library for Android. In debug everything works fine but only on release it's getting error as below for this library.
`java.lang.NoSuchFieldError: no "J" field "mNativeContext" in class "Lwseemann/media/FFmpegMediaMetadataRetriever;" or its superclasses
        at wseemann.media.FFmpegMediaMetadataRetriever.native_init(Native Method)
        at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(Unknown Source:43)
        at com.mybigday.rnmediameta.RNMediaMeta.getMetadata(Unknown Source:19)
        at com.mybigday.rnmediameta.RNMediaMeta.access$000(Unknown Source:0)
        at com.mybigday.rnmediameta.RNMediaMeta$1.run(Unknown Source:8)`

It's happening when I'm selecting video from media and passing path to `react-native-media-meta` this library. Every thing works fine in debug only release is getting failed. Please help.

**Comment by wseemann** [comment]
This sounds like it may be a proguard obfuscation issue since it only occurs on release builds. Have you tried building the release version without proguard?

**Comment by ganes1410** [comment]
@wseemann  The same issue happens for me too. I have built the app without proguard but still this happens.

**Comment by wseemann** [comment]
Closed due to inactivity.
