### ISSUE TITLE
<clinit> failed for class wseemann.media.FFmpegMediaMetadataRetriever

### ISSUE THREAD

**Issue by yinhaojun** [wseemann/FFmpegMediaMetadataRetriever#228]
```
  implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-core:1.0.15'
  implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.15'
```
and i add libavformat.so,libswscale.so, libavcodec.so and libavutil.so in jniLibs. But when i create FFmpegMediaMetadataRetriever, it crashed!

`java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     **Caused by: java.lang.NoClassDefFoundError: <clinit> failed for class wseemann.media.FFmpegMediaMetadataRetriever; see exception in other thread**
        at com.freedom.xiptv.tv.leanback.PlaybackSeekMetadataDataProvider$LoadBitmapAsyncTask.doInBackground(PlaybackSeekMetadataDataProvider.java:75)
        at com.freedom.xiptv.tv.leanback.PlaybackSeekMetadataDataProvider$LoadBitmapAsyncTask.doInBackground(PlaybackSeekMetadataDataProvider.java:63)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
`

If i remove `  implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.15'` and only add .so to jniLibs, it also crashed.

`java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
        Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "avpriv_mjpeg_val_dc" referenced by "/data/app/com.freedom.xiptv.tv-2/lib/arm/libavformat.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:124)
        at com.freedom.xiptv.tv.leanback.PlaybackSeekMetadataDataProvider$LoadBitmapAsyncTask.doInBackground(PlaybackSeekMetadataDataProvider.java:75)
        at com.freedom.xiptv.tv.leanback.PlaybackSeekMetadataDataProvider$LoadBitmapAsyncTask.doInBackground(PlaybackSeekMetadataDataProvider.java:63)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
`
Why?

**Comment by wseemann** [comment]
This should be resolved in version 1.0.19. Please submit a new issue of the problem persists.
