### ISSUE TITLE
Crash on `FFmpegMediaMetadataRetriever retriever = new  FFmpegMediaMetadataRetriever();` 

### ISSUE THREAD

**Issue by westlinkin** [wseemann/FFmpegMediaMetadataRetriever#43]
```
03-20 14:02:59.387  23585-23585/com.vtube.protube D/dalvikvm﹕ Trying to load lib /data/app-lib/com.vtube.protube-2/libavutil.so 0x41b386f8
03-20 14:02:59.387  23585-23585/com.vtube.protube D/dalvikvm﹕ Added shared lib /data/app-lib/com.vtube.protube-2/libavutil.so 0x41b386f8
03-20 14:02:59.387  23585-23585/com.vtube.protube D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.vtube.protube-2/libavutil.so 0x41b386f8, skipping init
03-20 14:02:59.387  23585-23585/com.vtube.protube D/dalvikvm﹕ Trying to load lib /data/app-lib/com.vtube.protube-2/libswscale.so 0x41b386f8
03-20 14:02:59.387  23585-23585/com.vtube.protube D/dalvikvm﹕ Added shared lib /data/app-lib/com.vtube.protube-2/libswscale.so 0x41b386f8
03-20 14:02:59.387  23585-23585/com.vtube.protube D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.vtube.protube-2/libswscale.so 0x41b386f8, skipping init
03-20 14:02:59.387  23585-23585/com.vtube.protube D/dalvikvm﹕ Trying to load lib /data/app-lib/com.vtube.protube-2/libavcodec.so 0x41b386f8
03-20 14:02:59.387  23585-23585/com.vtube.protube W/linker﹕ libavcodec.so has text relocations. This is wasting memory and is a security risk. Please fix.
03-20 14:02:59.397  23585-23585/com.vtube.protube D/dalvikvm﹕ Added shared lib /data/app-lib/com.vtube.protube-2/libavcodec.so 0x41b386f8
03-20 14:02:59.397  23585-23585/com.vtube.protube D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.vtube.protube-2/libavcodec.so 0x41b386f8, skipping init
03-20 14:02:59.397  23585-23585/com.vtube.protube D/dalvikvm﹕ Trying to load lib /data/app-lib/com.vtube.protube-2/libavformat.so 0x41b386f8
03-20 14:02:59.397  23585-23585/com.vtube.protube D/dalvikvm﹕ Added shared lib /data/app-lib/com.vtube.protube-2/libavformat.so 0x41b386f8
03-20 14:02:59.397  23585-23585/com.vtube.protube D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.vtube.protube-2/libavformat.so 0x41b386f8, skipping init
03-20 14:02:59.397  23585-23585/com.vtube.protube D/dalvikvm﹕ Trying to load lib /data/app-lib/com.vtube.protube-2/libffmpeg_mediametadataretriever_jni.so 0x41b386f8
03-20 14:02:59.397  23585-23585/com.vtube.protube D/dalvikvm﹕ Added shared lib /data/app-lib/com.vtube.protube-2/libffmpeg_mediametadataretriever_jni.so 0x41b386f8
03-20 14:02:59.397  23585-23585/com.vtube.protube E/dalvikvm﹕ ERROR: couldn't find native method
03-20 14:02:59.397  23585-23585/com.vtube.protube E/dalvikvm﹕ Requested: Lwseemann/media/FFmpegMediaMetadataRetriever;._setDataSource:(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V
03-20 14:02:59.397  23585-23585/com.vtube.protube E/MediaMetadataRetrieverJNI﹕ ERROR: FFmpegMediaMetadataRetriever native registration failed
03-20 14:02:59.397  23585-23585/com.vtube.protube W/dalvikvm﹕ Exception Ljava/lang/NoSuchMethodError; thrown while initializing Lwseemann/media/FFmpegMediaMetadataRetriever;
03-20 14:02:59.397  23585-23585/com.vtube.protube D/AndroidRuntime﹕ Shutting down VM
03-20 14:02:59.397  23585-23585/com.vtube.protube W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x416d3d58)
03-20 14:02:59.547  23585-23585/com.vtube.protube W/System.err﹕ java.lang.NoSuchMethodError: no static or non-static method "Lwseemann/media/FFmpegMediaMetadataRetriever;._setDataSource(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V"
03-20 14:02:59.547  23585-23585/com.vtube.protube W/System.err﹕ at java.lang.Runtime.nativeLoad(Native Method)
03-20 14:02:59.547  23585-23585/com.vtube.protube W/System.err﹕ at java.lang.Runtime.doLoad(Runtime.java:421)
03-20 14:02:59.547  23585-23585/com.vtube.protube W/System.err﹕ at java.lang.Runtime.loadLibrary(Runtime.java:362)
03-20 14:02:59.547  23585-23585/com.vtube.protube W/System.err﹕ at java.lang.System.loadLibrary(System.java:526)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:120)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at com.vtube.app.videoplay.async.ScreenShotTask.<init>(ScreenShotTask.java:39)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at com.vtube.component.YouTubeMediaControllerView$3.onClick(YouTubeMediaControllerView.java:305)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at android.view.View.performClick(View.java:4768)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at android.view.View$PerformClick.run(View.java:19073)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:755)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at android.os.Looper.loop(Looper.java:145)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5266)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
03-20 14:02:59.557  23585-23585/com.vtube.protube W/FlurryAgent﹕ Error logged: uncaught
03-20 14:02:59.557  23585-23585/com.vtube.protube W/FlurryAgent﹕ Ending session
03-20 14:02:59.557     909-1466/? W/com.android.server.location.LocationManagerMetrics﹕ recordProviderRunTime:providerName is null
    --------- beginning of /dev/log/system
03-20 14:02:59.567  23585-23585/com.vtube.protube E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.vtube.protube, PID: 23585
    java.lang.NoSuchMethodError: no static or non-static method "Lwseemann/media/FFmpegMediaMetadataRetriever;._setDataSource(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V"
            at java.lang.Runtime.nativeLoad(Native Method)
            at java.lang.Runtime.doLoad(Runtime.java:421)
            at java.lang.Runtime.loadLibrary(Runtime.java:362)
            at java.lang.System.loadLibrary(System.java:526)
            at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:120)
            at com.vtube.app.videoplay.async.ScreenShotTask.<init>(ScreenShotTask.java:39)
            at com.vtube.component.YouTubeMediaControllerView$3.onClick(YouTubeMediaControllerView.java:305)
            at android.view.View.performClick(View.java:4768)
            at android.view.View$PerformClick.run(View.java:19073)
            at android.os.Handler.handleCallback(Handler.java:755)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5266)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
            at dalvik.system.NativeStart.main(Native Method)
```

I put all the files in pre-build libs folder into my projects libs folder.

Android Studio 1.2 Preview 3 (AI - 141.1793788)

**Comment by wseemann** [comment]
What version of Android are you using?

**Comment by westlinkin** [comment]
Android 4.2.2

**Comment by wseemann** [comment]
Can you download the latest prebuilt-libs (I just uploaded them today) and try again? I tested using the emulator and I can't reproduce this issue. Make sure you delete any old JARs and .so file from your apps "libs" before adding the new ones. Test again and let me know.

**Comment by westlinkin** [comment]
OK, I'll try them later today. Thanks.

**Comment by westlinkin** [comment]
The same crash.

**Comment by wseemann** [comment]
If you want to send me your code I will test it out however running this on the armeabi-v7a 4.2.2 emulator doesn't produce a crash. I would appear you may have a sync issue between the native .so files and fmmr.jar.

**Comment by AbigailEsman** [comment]
same issue for me.

**Comment by AbigailEsman** [comment]
I added gradle import line in build.gradle of app module.
compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.3'

**Comment by fxhereng** [comment]
Same problem for me with the 1.0.8 with a 4.4.2 api 19 device. Put it back to 1.0.3 version seems to have fixed the problem.

Cheers

**Comment by AlexRodri** [comment]
Same problem for me with the 1.0.11 with a 4.4.2 api 19 device. only happens when in release.

Would appreciate your help.

**Comment by wseemann** [comment]
Can you post you crash from logcat?

**Comment by AlexRodri** [comment]
`07-15 17:28:10.644 16103-16103/esrg.digitalsignage.standbyplayer E/dalvikvm: ERROR: couldn't find native method
07-15 17:28:10.644 16103-16103/esrg.digitalsignage.standbyplayer E/dalvikvm: Requested: Lwseemann/media/FFmpegMediaMetadataRetriever;._setDataSource:(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V
07-15 17:28:10.644 16103-16103/esrg.digitalsignage.standbyplayer E/MediaMetadataRetrieverJNI: ERROR: FFmpegMediaMetadataRetriever native registration failed



07-15 17:28:10.644 16103-16103/esrg.digitalsignage.standbyplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: esrg.digitalsignage.standbyplayer, PID: 16103
                                                                                   java.lang.NoSuchMethodError: no static or non-static method "Lwseemann/media/FFmpegMediaMetadataRetriever;._setDataSource(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V"
                                                                                       at java.lang.Runtime.nativeLoad(Native Method)
                                                                                       at java.lang.Runtime.doLoad(Runtime.java:421)
                                                                                       at java.lang.Runtime.loadLibrary(Runtime.java:362)
                                                                                       at java.lang.System.loadLibrary(System.java:526)
                                                                                       at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(Unknown Source)
                                                                                       at esrg.digitalsignage.standbyplayer.e.a.a(Unknown Source)
                                                                                       at esrg.digitalsignage.standbyplayer.e.a.a(Unknown Source)
                                                                                       at esrg.digitalsignage.standbyplayer.e.a.j(Unknown Source)
                                                                                       at android.support.a.a.m.B(Unknown Source)
                                                                                       at android.support.a.a.w.a(Unknown Source)
                                                                                       at android.support.a.a.w.a(Unknown Source)
                                                                                       at android.support.a.a.w.a(Unknown Source)
                                                                                       at android.support.a.a.w.m(Unknown Source)
                                                                                       at android.support.a.a.p.b(Unknown Source)
                                                                                       at android.support.a.a.p.onPostResume(Unknown Source)
                                                                                       at android.app.Activity.performResume(Activity.java:5344)
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2764)
                                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
                                                                                       at dalvik.system.NativeStart.main(Native ### Method)`

**Comment by AlexRodri** [comment]
Thank you for your help!

**Comment by AlexRodri** [comment]
Problem fixed!

It's a Proguard issue, add the following line to the "proguard-rules.txt":

`-keep class wseemann.media.** { *; }`

Cheers
