### ISSUE TITLE
setDataSource failed: status = 0xFFFFFFFF when loading from APK expansion

### ISSUE THREAD

**Issue by danieljonker** [wseemann/FFmpegMediaMetadataRetriever#57]
This appears similar to #20. When trying to use FFmpegMediaMetadataRetriever in the same fashion as the android MediaMetadataRetriever (I literally just swap one for the other) it causes the error.

Here is the method:

```
public static final Bitmap getThumbnailFromUri(Context context, Uri uri) {
        Log.d(TAG, "getThumbnailFromUri");
        MediaMetadataRetriever retriever = new MediaMetadataRetriever();
        try {
            retriever.setDataSource(context, uri);
            Bitmap bitmap = retriever
                    .getFrameAtTime(100000, MediaMetadataRetriever.OPTION_PREVIOUS_SYNC);
            return bitmap;
        } finally {
            retriever.release();
        }
    }
```

and the error:
```
06-23 09:44:39.354: I/MediaMetadataRetrieverJNI(14008): release
06-23 09:44:39.354: D/AndroidRuntime(14008): Shutting down VM
06-23 09:44:39.354: W/dalvikvm(14008): threadid=1: thread exiting with uncaught exception (group=0x4161fce0)
06-23 09:44:39.364: E/AndroidRuntime(14008): FATAL EXCEPTION: main
06-23 09:44:39.364: E/AndroidRuntime(14008): Process: au.com.datacom.kimberley, PID: 14008
06-23 09:44:39.364: E/AndroidRuntime(14008): java.lang.RuntimeException: Unable to start activity ComponentInfo{au.com.datacom.kimberley/au.com.datacom.kimberley.Main.AboutActivity}: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFFF
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.os.Looper.loop(Looper.java:136)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at dalvik.system.NativeStart.main(Native Method)
06-23 09:44:39.364: E/AndroidRuntime(14008): Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFFF
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(Native Method)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(FFmpegMediaMetadataRetriever.java:243)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at au.com.datacom.kimberley.Manager.FKResourceManager.getThumbnailFromUri(FKResourceManager.java:195)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at au.com.datacom.kimberley.Main.AboutActivity.onCreate(AboutActivity.java:84)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.app.Activity.performCreate(Activity.java:5231)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
06-23 09:44:39.364: E/AndroidRuntime(14008): 	... 11 more
```

Should I attempt to write a sample app to demo bug?

**Comment by wseemann** [comment]
This isn't a bug, you are passing an invalid URI to `setDataSource` and you don't have a catch statement in your code to handle the resulting exception.

**Comment by LiuPangYao** [comment]
retriever.setDataSource(context, uri);
I have the sama problem, check the uri is correct.
if the video is .mp4 is ok, but .mov is wrong.
i think my case is not invalid URI cause
