### ISSUE TITLE
Failed in release

### ISSUE THREAD

**Issue by KonstantinBerkow** [wseemann/FFmpegMediaMetadataRetriever#61]
I am using library via gradle(compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.1'), using in debug totally OK. But when trying to use it in release, with proguard, throws exception:
Caused by: java.lang.NoSuchMethodError: no static or non-static method "Lwseemann/media/FFmpegMediaMetadataRetriever;._setDataSource(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V"
            at java.lang.Runtime.nativeLoad(Native Method)
            at java.lang.Runtime.doLoad(Runtime.java:435)
            at java.lang.Runtime.loadLibrary(Runtime.java:363)
            at java.lang.System.loadLibrary(System.java:526)
            at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(Unknown Source)
            at com.dowell.pickplay.e.a.a(Unknown Source)
            at com.dowell.pickplay.e.a.loadInBackground(Unknown Source)
            at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
            at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
            at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
Using jar from demo does not solves problem.

I've tried to add this to proguard, didn't help.
-keepclasseswithmembernames,includedescriptorclasses class wseeman.media.* {
    native \<methods\>;
}

Actual piece of code:
FFmpegMediaMetadataRetriever retriever = new FFmpegMediaMetadataRetriever();
                    retriever.setDataSource(dataPath);
                    Log.i(TAG, "metadata: " + retriever.getMetadata().getAll());
                    retriever.release();

**Comment by wseemann** [comment]
This is fixed in the latest release.
