### ISSUE TITLE
UnsatisfiedLinkError with API 23

### ISSUE THREAD

**Issue by Uscher1** [wseemann/FFmpegMediaMetadataRetriever#69]
I get the following runtime exception when using compileSdkVersion 23:
```
10-30 10:16:48.831 5102-5102/ch.ecosoft.fmmrtest E/AndroidRuntime: FATAL EXCEPTION: main
10-30 10:16:48.831 5102-5102/ch.ecosoft.fmmrtest E/AndroidRuntime: Process: ch.ecosoft.fmmrtest, PID: 5102
10-30 10:16:48.831 5102-5102/ch.ecosoft.fmmrtest E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/ch.ecosoft.fmmrtest-1/lib/arm/libavcodec.so: has text relocations
10-30 10:16:48.831 5102-5102/ch.ecosoft.fmmrtest E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:372)
10-30 10:16:48.831 5102-5102/ch.ecosoft.fmmrtest E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:1076)
10-30 10:16:48.831 5102-5102/ch.ecosoft.fmmrtest E/AndroidRuntime:     at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:120)
10-30 10:16:48.831 5102-5102/ch.ecosoft.fmmrtest E/AndroidRuntime:     at ch.ecosoft.fmmrtest.MainActivity.onCreate(MainActivity.java:36)
```
I tried it with maven dependency 
```
compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.1' 
```
and also with the appropriate AAR files.

Please find the demo project here: https://www.asuswebstorage.com/navigate/s/9A43405AC2834556912CC75AA1B4CFCBW

Probably you are aware of the issue and have a quick answer. Thank you.

**Comment by wseemann** [comment]
Fixed in latest release.

    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.2'

**Comment by Uscher1** [comment]
Still the same problem with version 1.0.2.

**Comment by abuharsky** [comment]
still the same problem on 1.0.2

```
FATAL EXCEPTION: main
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: Process: com.testplayer, PID: 32343
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.testplayer-1/lib/arm/libavcodec.so: has text relocations
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at java.lang.Runtime.loadLibrary(Runtime.java:372)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at java.lang.System.loadLibrary(System.java:1076)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at wseemann.media.FFmpegMediaMetadataRetriever.<clinit😠FFmpegMediaMetadataRetriever.java:120)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at com.testplayer.models.player.StreamMetadataLoader.start(StreamMetadataLoader.java:40)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at com.testplayer.models.player.Player$2.onStatusChanged(Player.java:86)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at com.testplayer.MediaPlayerWrapper$1.onPrepared(MediaPlayerWrapper.java:35)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2816)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at android.os.Looper.loop(Looper.java:148)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:5417)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-18 16:16:28.511 32343-32343/com.testplayer E/AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dany-kun** [comment]
Unfortunately, if we look at [this ticket](https://trac.ffmpeg.org/ticket/4928); it does not seem there won't be any good solution soon
