### ISSUE TITLE
Constructor not working in Android 6.0 (Marshmallow)

### ISSUE THREAD

**Issue by mateusgrb** [wseemann/FFmpegMediaMetadataRetriever#86]
In an android emulator 6.0, I'm trying to instantiate a FFmpegMediaMetadataRetriever object like below:
FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();

but this command is shutting down the thread. I wrapped the call in a try catch to get the exception but it's not working.

I'm running the app in Android 6.0 and I believe that's causing the issue. Any ideas on how to solve that?

**Comment by wseemann** [comment]
Can you post a stack trace with the error?

**Comment by mateusgrb** [comment]
FATAL EXCEPTION: main
                                                                        Process: com.example.streamingapp, PID: 3034
                                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.streamingapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.streamingapp-1/lib/x86_64, /data/app/com.example.streamingapp-1/base.apk!/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libavutil.so"
                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                            at java.lang.System.loadLibrary(System.java:1076)
                                                                            at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:120)
                                                                            at com.example.streamingapp.activities.MainActivity.onCreate(MainActivity.java:139)
                                                                            at android.app.Activity.performCreate(Activity.java:6237)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mateusgrb** [comment]
It looks like a compatibility problem with Android 6.0.

**Comment by mateusgrb** [comment]
Hey @wseemann , were you able to reproduce this bug in android 6 too?

**Comment by AbigailEsman** [comment]
yes, its crashing at my side too
Seems its not loading jni lirbaries such as "avutil"

**Comment by wseemann** [comment]
x86_64 support was added in v1.0.4.

**Comment by shaileshmulange** [comment]
@wseemann We are getting some unexpected experience with "Marshmallow 6.0.1". I have found same crash on some device but some device is working properly.It is working on my device but not on friend device both have the same version "Marshmallow 6.0.1".
Now I am using our Marshmallow 6.0 compatible version of the library.

compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.6'

**Comment by wseemann** [comment]
Why are you using version 1.0.6?

**Comment by shaileshmulange** [comment]
If I used lower than this version it is not working on Marshmallow, so I am using 1.0.6.
