### ISSUE TITLE
UnsatisfiedLinkError after proguard run

### ISSUE THREAD

**Issue by Pawly** [wseemann/FFmpegMediaMetadataRetriever#88]
Hi,

I got that error after I've run proguard and startet the app on FireTv.

>  java.lang.UnsatisfiedLinkError: dlopen failed: library "libavutil.so.54" not found
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                       at java.lang.System.loadLibrary(System.java:988)
                                                       at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(Unknown Source)
...
>
I added the necessary files to my project in Android Studio as following:

app->libs->fmmr.jar

added all .so files from the prebuilt-aars.zip file in that directories:

app->src->main->jniLibs->armeabi
app->src->main->jniLibs->armeabi-v7a
app->src->main->jniLibs->mips
app->src->main->jniLibs->x86
app->src->main->jniLibs->x86_64

Any help appreciated

**Comment by wseemann** [comment]
FFmpegMediaMetadataRetriever doesn't support proguard.
