### ISSUE TITLE
Failed to register native method wseemann.media.FFmpegMediaMetadataRetriever.setDataSource

### ISSUE THREAD

**Issue by dvg4000** [wseemann/FFmpegMediaMetadataRetriever#93]
Hi.

I',m getting this error when trying to use FFmpegMediaMetadataRetriever.

```
E/art: ----- class 'Lwseemann/media/FFmpegMediaMetadataRetriever;' cl=0x12c53cc0 -----
E/art:   objectSize=428 (412 from super)
E/art:   access=0x8008.0001
E/art:   super='java.lang.Class<java.lang.Object>' (cl=0x0)
E/art:   vtable (4 entries, 11 in super):
E/art:      0: void wseemann.media.FFmpegMediaMetadataRetriever.finalize()
E/art:      1: android.graphics.Bitmap wseemann.media.FFmpegMediaMetadataRetriever.getFrameAtTime(long)
E/art:      2: void wseemann.media.FFmpegMediaMetadataRetriever.release()
E/art:      3: void wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(java.lang.String, java.util.Map)
E/art:   direct methods (7 entries):
E/art:      0: void wseemann.media.FFmpegMediaMetadataRetriever.<clinit>()
E/art:      1: void wseemann.media.FFmpegMediaMetadataRetriever.<init>()
E/art:      2: byte[] wseemann.media.FFmpegMediaMetadataRetriever._getFrameAtTime(long, int)
E/art:      3: void wseemann.media.FFmpegMediaMetadataRetriever._setDataSource(java.lang.String, java.lang.String[], java.lang.String[])
E/art:      4: void wseemann.media.FFmpegMediaMetadataRetriever.native_finalize()
E/art:      5: void wseemann.media.FFmpegMediaMetadataRetriever.native_init()
E/art:      6: void wseemann.media.FFmpegMediaMetadataRetriever.native_setup()
E/art:   static fields (1 entries):
E/art:      0: java.lang.String[] wseemann.media.FFmpegMediaMetadataRetriever.JNI_LIBRARIES
E/art: Failed to register native method wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(Ljava/lang/String;)V in /data/app/com.project.app.android-1/base.apk:classes2.dex
E/MediaMetadataRetrieverJNI: ERROR: FFmpegMediaMetadataRetriever native registration failed
E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
                 Process: com.project.app.android, PID: 8599
                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                     at java.lang.Thread.run(Thread.java:818)
                  Caused by: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.project.app.android-1/lib/x86/libffmpeg_mediametadataretriever_jni.so"
                     at java.lang.Runtime.loadLibrary(Runtime.java:371)
                     at java.lang.System.loadLibrary(System.java:988)
                     at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:124)
                     at com.project.app.android.content.video.package$.com$project$app$android$content$video$package$$fetchFrame(package.scala:44)
                     at com.project.app.android.content.video.package$$anonfun$com$project$app$android$content$video$package$$getFrame$1.apply(package.scala:38)
                     at com.project.app.android.content.video.package$$anonfun$com$project$app$android$content$video$package$$getFrame$1.apply(package.scala:38)
                     at scala.Option.fold(Option.scala:158)
                     at com.project.app.android.content.video.package$.com$project$app$android$content$video$package$$getFrame(package.scala:38)
                     at com.project.app.android.content.video.package$$anonfun$getVideoFrame$1.apply(package.scala:23)
                     at com.project.app.android.content.video.package$$anonfun$getVideoFrame$1.apply(package.scala:22)
                     at rx.lang.scala.ImplicitFunctionConversions$$anon$1.call(ImplicitFunctionConversions.scala:53)
                     at rx.lang.scala.ImplicitFunctionConversions$$anon$1.call(ImplicitFunctionConversions.scala:51)
                     at rx.Observable.unsafeSubscribe(Observable.java:8098)
                     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
```

Here is my code (Scala):
```
val mmr = new FFmpegMediaMetadataRetriever()
try {
  mmr.setDataSource(url.value.text, new java.util.HashMap[String, String]())
  val frame = mmr.getFrameAtTime(TimeUnit.MICROSECONDS.convert(1, TimeUnit.SECONDS))
  /*
  doBitmapStuff(frame)
  */
} finally {
  mmr.release()
}
```

Here is `gradle.build`:
```
compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.6'
```

And i added `arr`s form `prebuilt-aars-with-https.zip` to `app/libs`.

**Comment by dvg4000** [comment]
`-keep class wseemann.media.** { *; }` fixed problem. 
Thanks. :)
